### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by ZhimaoPeng** [Mathux/ACTOR#2]
When I try to render the generated motions. I got the following error:

(actor) nankaingy@lza-PC:~/data/code/pose-shape/ACTOR$ python -m src.render.rendermotion pretrained_models/humanact12/generation.npy
Visualize generation_0, action 0:   0%|                                        | 0/60 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/nankaingy/data/code/pose-shape/ACTOR/src/render/rendermotion.py", line 92, in <module>
    main()
  File "/home/nankaingy/data/code/pose-shape/ACTOR/src/render/rendermotion.py", line 88, in main
    render_video(meshes, key, action, renderer, path, background)
  File "/home/nankaingy/data/code/pose-shape/ACTOR/src/render/rendermotion.py", line 27, in render_video
    img = renderer.render(background, mesh, cam, color=color)
  File "/home/nankaingy/data/code/pose-shape/ACTOR/src/render/renderer.py", line 143, in render
    rgb, _ = self.renderer.render(self.scene, flags=render_flags)
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/pyrender/offscreen.py", line 99, in render
    return self._renderer.render(scene, flags)
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/pyrender/renderer.py", line 121, in render
    self._update_context(scene, flags)
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/pyrender/renderer.py", line 709, in _update_context
    p._add_to_context()
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/pyrender/primitive.py", line 324, in _add_to_context
    self._vaid = glGenVertexArrays(1)
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
    if self.load():
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 383, in load
    func = platform.PLATFORM.constructFunction(
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 148, in constructFunction
    if (not is_core) and not self.checkExtension( extension ):
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/platform/baseplatform.py", line 270, in checkExtension
    result = extensions.ExtensionQuerier.hasExtension( name )
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/extensions.py", line 98, in hasExtension
    result = registered( specifier )
  File "/home/nankaingy/data/anaconda3/envs/actor/lib/python3.8/site-packages/OpenGL/extensions.py", line 105, in __call__
    if not specifier.startswith( self.prefix ):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

Anyone can help?

Thanks in advance!

**Comment by Mathux** [comment]
The problem is related to ``pyrender`` which depends on the ``OpenGL`` engine to work properly. Please see their installation guide for help at this address: https://pyrender.readthedocs.io/en/latest/install/index.html.
If you want to render on an ssh server without a screen, please see this web page which may help you: https://pyrender.readthedocs.io/en/latest/examples/offscreen.html.
